copy ..\Hansoft-Jean-AssignReleaseRiskBehavior\bin\x86\Debug\AssignReleaseRiskBehavior.dll %1
copy ..\Hansoft-Jean-CloneProjectBehavior\bin\x86\Debug\CloneProjectBehavior.dll %1
copy ..\Hansoft-Jean-CopyBehavior\bin\x86\Debug\CopyBehavior.dll %1
copy ..\Hansoft-Jean-DefaultValueBehavior\bin\x86\Debug\DefaultValueBehavior.dll %1
copy ..\Hansoft-Jean-DeriveBehavior\bin\x86\Debug\DeriveBehavior.dll %1
copy ..\Hansoft-Jean-DerivedColumnExpressionExample\bin\x86\Debug\DerivedColumnExpressionExample.dll %1
copy ..\Hansoft-Jean-IntermediateRankBehavior\bin\Debug\IntermediateRankBehavior.dll %1
copy ..\Hansoft-Jean-NumberBehavior\bin\x86\Debug\NumberBehavior.dll %1
copy ..\Hansoft-Jean-ShadowBacklogBehavior\bin\Debug\ShadowBacklogBehavior.dll %1
copy ..\Hansoft-Jean-TrackLastStatusChangeBehavior\bin\x86\Debug\TrackLastStatusChangeBehavior.dll %1
copy ..\HansoftSDK\Win32\HPMSdk.x86.dll %1
copy ..\HansoftSDK\\Win32\HPMSdkManaged_4_5.x86.dll %1
